import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { title, description, neighborhood, state } = await req.json().catch(() => {
      // If JSON parsing fails, try to get params from URL
      const url = new URL(req.url);
      return {
        title: decodeURIComponent(url.searchParams.get('title') || ''),
        description: decodeURIComponent(url.searchParams.get('description') || ''),
        neighborhood: decodeURIComponent(url.searchParams.get('neighborhood') || ''),
        state: url.searchParams.get('state') || 'created',
      };
    });
    
    const LOVABLE_API_KEY = Deno.env.get('LOVABLE_API_KEY');
    if (!LOVABLE_API_KEY) {
      throw new Error('LOVABLE_API_KEY not configured');
    }

    // Determine the image prompt based on state
    let imagePrompt = '';
    
    if (state === 'locked') {
      imagePrompt = `Create a vibrant, modern social media share card (1200x630px) with a celebration theme. 
      
Design requirements:
- Bold, eye-catching gradient background (purple to blue)
- Large, centered text: "${title}"
- Subtitle below: "${description}"
- Location badge: "${neighborhood}"
- Include checkmark or lock icon to indicate confirmed plans
- Modern, clean typography
- Leave space for text overlays
- Professional social media aesthetic
- High contrast for readability`;
    } else if (state === 'nearlock') {
      imagePrompt = `Create an exciting, modern social media share card (1200x630px) with an urgent, energetic theme.
      
Design requirements:
- Bold gradient background (orange to pink)
- Large, centered text: "${title}"
- Subtitle: "${description}"
- Location: "${neighborhood}"
- Include clock or timer visual element
- Urgent but friendly vibe
- Modern typography
- High contrast colors
- Professional social media aesthetic`;
    } else {
      imagePrompt = `Create an inviting, modern social media share card (1200x630px) for voting on plans.
      
Design requirements:
- Warm, friendly gradient background (teal to blue)
- Large, centered text: "${title}"
- Subtitle: "${description}"
- Location badge: "${neighborhood}"
- Include vote or poll visual elements (hands raised, checkboxes)
- Friendly, approachable design
- Modern, clean typography
- High contrast for readability
- Professional social media aesthetic`;
    }

    console.log('Generating OG image with Lovable AI:', { title, state });

    const response = await fetch('https://ai.gateway.lovable.dev/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${LOVABLE_API_KEY}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: 'google/gemini-2.5-flash-image-preview',
        messages: [
          {
            role: 'user',
            content: imagePrompt
          }
        ],
        modalities: ['image', 'text']
      }),
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error('Lovable AI error:', response.status, errorText);
      
      if (response.status === 429) {
        return new Response(
          JSON.stringify({ error: 'Rate limit exceeded. Please try again later.' }),
          { status: 429, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
        );
      }
      
      if (response.status === 402) {
        return new Response(
          JSON.stringify({ error: 'Payment required. Please add credits to your workspace.' }),
          { status: 402, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
        );
      }
      
      throw new Error(`AI gateway error: ${response.status}`);
    }

    const data = await response.json();
    const imageUrl = data.choices?.[0]?.message?.images?.[0]?.image_url?.url;

    if (!imageUrl) {
      console.error('No image generated:', data);
      throw new Error('No image generated by AI');
    }

    console.log('OG image generated successfully');

    // Extract the base64 data and return it as a PNG
    const base64Data = imageUrl.split(',')[1];
    const imageBuffer = Uint8Array.from(atob(base64Data), c => c.charCodeAt(0));

    return new Response(imageBuffer, {
      headers: {
        ...corsHeaders,
        'Content-Type': 'image/png',
        'Cache-Control': 'public, max-age=3600',
      },
    });
  } catch (error) {
    console.error('Error generating OG image:', error);
    return new Response(
      JSON.stringify({ error: error instanceof Error ? error.message : 'Unknown error' }),
      { 
        status: 500,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      }
    );
  }
});
